### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by JasonTheAdams** [DekodeInteraktiv/localwp-projectbase-addon#2]
Greetings!

This looks really useful! But I can't seem to figure out how to install it. I followed the instructions by going to 1.0.0 release and downloading release.zip. I then opened LocalWP and clicked "Install from disk", but it won't allow me to select a zip as the add-on file. I then tried extracting the release.zip, but non of the contents were something I could install either.

I'm sure I'm missing something simple. Mind pointing me in the right direction? 😄

**Comment by isuke01** [comment]
Hi @JasonTheAdams  I had same issue.
Use [release.tar.gz](https://github.com/DekodeInteraktiv/localwp-projectbase-addon/releases/download/1.0.0/release.tar.gz)  instead of .zip 😄

**Comment by JasonTheAdams** [comment]
That did it! For others:
1. Download the .tar.gz file
2. Go to LocalWP > Add-ons > Installed
3. Select the downloaded .tar.gz file
4. Give it 5-10 seconds to install (it may not look like it's doing much)
5. 💥
